services:


  web:
    build: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 2000:2000
    environment:
      - DATABASE_URI=postgresql+psycopg2://postgres:postgres@db:5432/DB


  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB
    ports:
      - '5400:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5