"""essage=add username

Revision ID: 6b64f247452b
Revises: 9f6009bc1542
Create Date: 2024-06-29 15:32:03.893173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b64f247452b'
down_revision: Union[str, None] = '9f6009bc1542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertgdata', sa.Column('username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usertgdata', 'username')
    # ### end Alembic commands ###
